msgid "cceErrorSentence"
msgstr "对不起，出现内部服务器错误。"

msgid "cceHandlerErrorSentence"
msgstr "对不起，出现内部服务器错误。[[base-sauce-basic.contactTechSupport]]"

msgid "unknownAttr"
msgstr "[[base-cce.cceErrorSentence]] 属性[[VAR.key]]未知。[[base-sauce-basic.contactTechSupport]]"

msgid "unknownClass"
msgstr "[[base-cce.cceErrorSentence]] 类[[VAR.key]]未知。[[base-sauce-basic.contactTechSupport]]"

msgid "unknownNs"
msgstr "[[base-cce.cceErrorSentence]] 名称空间[[VAR.key]]未知。[[base-sauce-basic.contactTechSupport]]"

msgid "unknownOid"
msgstr "[[base-cce.cceErrorSentence]] 对象[[VAR.oid]]未知。[[base-sauce-basic.contactTechSupport]]"

msgid "permissionDenied"
msgstr "[[base-cce.cceErrorSentence]][[VAR.key]]许可被拒绝。[[base-sauce-basic.contactTechSupport]]"

msgid "unknownErrorCode"
msgstr "[[base-cce.cceErrorSentence]] 出现未知错误。[[base-sauce-basic.contactTechSupport]]"

msgid "invalidType"
msgstr "[[base-cce.cceErrorSentence]] 类型[[VAR.key]]无效。[[base-sauce-basic.contactTechSupport]]"

	# User input invalid but validation fell through
msgid "invalidData"
msgstr "对不起，字段[[VAR.key]]中输入的数据无效。请检查输入的内容并重试。"

msgid "outOfMemory"
msgstr "[[base-cce.cceErrorSentence]] 系统无法分配足够的内存以继续操作。"

